apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-data
  namespace: scm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mycluster-storage
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: scm
  labels:
    name: redis
spec:
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      name: redis
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: sameersbn/redis
        //redis:7.0.13
        imagePullPolicy: IfNotPresent
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-pvc-data
        //nfs:
          //server: 192.168.59.170
          //path: /data/gitlabDB/redis
          //readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: scm
  labels:
    name: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    name: redis
