apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: cicd
  name: gitlab-pv
  labels:
    app: gitlab-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.59.170
    path: /data/gitlabdata/gitlab

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cicd
  name: gitlab-pvc
  labels:
    app: gitlab-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      app: gitlab-pv
