apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: cicd
  name: redis-pv
  labels:
    app: redis-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/gitlabdata/redis
    server: 192.168.59.170

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cicd
  name: redis-pvc
  labels:
    app: redis-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: redis-pv

