apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: cicd
  name: postsql-pv
  labels:
    app: postsql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/gitlabdata/postgresql
    server: 192.168.59.170

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cicd
  name: postsql-pvc
  labels:
    app: postsql-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: postsql-pv

