---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs-mycluster-storage
  finalizers:
    - kubernetes.io/pv-protection
  name: pvc-fa3124c4-6d7a-4bdc-b08c-03bc05293e38
  resourceVersion: '944212'
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 25Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: gitlab-pvc-data
    namespace: scm
    resourceVersion: '944204'
    uid: fa3124c4-6d7a-4bdc-b08c-03bc05293e38
  nfs:
    path: /data/scm-gitlab-pvc-data-pvc-fa3124c4-6d7a-4bdc-b08c-03bc05293e38
    server: 192.168.59.170
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mycluster-storage
  volumeMode: Filesystem
status:
  phase: Bound

