---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    name: redis
  name: redis
  namespace: scm
  resourceVersion: '683731'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: redis
      name: redis
    spec:
      containers:
        - image: sameersbn/redis
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: redis
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/redis
              name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-pvc-data
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2023-12-09T17:15:55Z'
      lastUpdateTime: '2023-12-09T17:16:06Z'
      message: ReplicaSet "redis-787948cb9b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2023-12-10T09:56:23Z'
      lastUpdateTime: '2023-12-10T09:56:23Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: redis
  name: redis
  namespace: scm
  resourceVersion: '662519'
spec:
  clusterIP: 10.96.244.106
  clusterIPs:
    - 10.96.244.106
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
  selector:
    name: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

