apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scm
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:2.414.1
          ports:
            - containerPort: 8080
            - containerPort: 50000
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: scm
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 18088
      targetPort: 8080
  type: LoadBalancer

