apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scm
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: daocloud.io/library/nginx:1.19.1
        ports:
        - containerPort: 80
