apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scm
  name: tomcat
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: daocloud.io/library/tomcat:8.5.57
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: scm
  name: tomcat
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
  ports:
  - port: 19090
    targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: scm
  name: tomcat
spec:
  ingressClassName: myingress
  rules:
  - host: itwst.com 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tomcat
            port:
              number: 19090
