apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: scm
  name: pv-nfs-scm
  labels:
    app: pv-nfs-scm
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.59.170
    path: /data
