apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: scm
  name: pvc-nfs-scm
  labels:
    app: pvc-nfs-scm
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
     storage: 30Gi
  selector:
    matchLabels:
      app: pv-nfs-scm
