apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: cicd
  name: jenkins-pv
  labels:
    app: jenkins-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.59.170
    path: /data/jenkinsdata

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cicd
  name: jenkins-pvc
  labels:
    app: jenkins-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: jenkins-pv
